/** Manchester-area neighbourhoods used for market lookups (must match JSON keys). */
export const NEIGHBOURHOODS = [
  "Ancoats and Clayton",
  "Ardwick",
  "Baguley",
  "Bolton District",
  "Bradford",
  "Brooklands",
  "Burnage",
  "Bury District",
  "Charlestown",
  "Cheetham",
  "Chorlton",
  "Chorlton Park",
  "City Centre",
  "Crumpsall",
  "Didsbury East",
  "Didsbury West",
  "Fallowfield",
  "Gorton North",
  "Gorton South",
  "Harpurhey",
  "Higher Blackley",
  "Hulme",
  "Levenshulme",
  "Longsight",
  "Miles Platting and Newton Heath",
  "Moss Side",
  "Moston",
  "Northenden",
  "Old Moat",
  "Oldham District",
  "Rochdale District",
  "Rusholme",
  "Salford District",
  "Sharston",
  "Stockport District",
  "Tameside District",
  "Trafford District",
  "Whalley Range",
  "Wigan District",
  "Withington",
  "Woodhouse Park",
] as const;

export type Neighbourhood = (typeof NEIGHBOURHOODS)[number];
